require('dotenv').config()
const express = require('express')
const cors = require('cors')
const connectDB = require('./config/database')
const authRoutes        = require('./routes/auth')
const categoriasRoutes  = require('./routes/categorias')
const productosRoutes   = require('./routes/productos')
const ingredientesRoutes = require('./routes/ingredientes')
const zonasRoutes       = require('./routes/zonas')
const mesasRoutes       = require('./routes/mesas')
const ventasRoutes      = require('./routes/ventas')
const gastosRoutes      = require('./routes/gastos')
const stockRoutes       = require('./routes/stock')
const proveedoresRoutes    = require('./routes/proveedores')
const uploadsRoutes        = require('./routes/uploads')
const cartaRoutes          = require('./routes/carta')
const pedidosOnlineRoutes  = require('./routes/pedidosOnline')
const adminRoutes          = require('./routes/admin')
const configRoutes         = require('./routes/config')
const mostradorRoutes      = require('./routes/mostrador')
const deliveryRoutes       = require('./routes/delivery')
const descuentosRoutes        = require('./routes/descuentos')
const categoriasGastoRoutes   = require('./routes/categoriasGasto')
const clientesRoutes                      = require('./routes/clientes')
const cuentasCorrientesRoutes             = require('./routes/cuentasCorrientes')
const cuentasCorrientesProveedoresRoutes  = require('./routes/cuentasCorrientesProveedores')

const app = express()
const PORT = process.env.PORT || 3000

connectDB()

app.use(cors())
app.use(express.json())

app.use('/auth', authRoutes)
app.use('/api/categorias',   categoriasRoutes)
app.use('/api/productos',    productosRoutes)
app.use('/api/ingredientes', ingredientesRoutes)
app.use('/api/zonas',        zonasRoutes)
app.use('/api/mesas',        mesasRoutes)
app.use('/api/ventas',       ventasRoutes)
app.use('/api/gastos',       gastosRoutes)
app.use('/api/stock',        stockRoutes)
app.use('/api/proveedores',    proveedoresRoutes)
app.use('/api/uploads',       uploadsRoutes)
app.use('/uploads',           express.static(require('path').join(__dirname, '../uploads')))
app.use('/api/carta',          cartaRoutes)
app.use('/api/pedidos-online', pedidosOnlineRoutes)
app.use('/api/admin',          adminRoutes)
app.use('/api/config',         configRoutes)
app.use('/api/mostrador',      mostradorRoutes)
app.use('/api/delivery',       deliveryRoutes)
app.use('/api/descuentos',         descuentosRoutes)
app.use('/api/categorias-gasto',   categoriasGastoRoutes)
app.use('/api/clientes',                        clientesRoutes)
app.use('/api/cuentas-corrientes',              cuentasCorrientesRoutes)
app.use('/api/cuentas-corrientes-proveedores',  cuentasCorrientesProveedoresRoutes)

app.get('/', (req, res) => {
  res.json({ message: 'FoodOps API running' })
})

app.get('/setup-admin', async (req, res) => {
  try {
    const bcrypt = require('bcryptjs')
    const User = require('./models/User')
    const existe = await User.findOne({ email: 'admin@gmail.com' })
    if (existe) return res.json({ message: 'Admin ya existe' })
    const password = await bcrypt.hash('admin', 10)
    await User.create({ nombre: 'Admin', email: 'admin@gmail.com', password, restaurante: 'FoodOps Admin', plan: 'premium', role: 'admin' })
    res.json({ message: 'Admin creado: admin@gmail.com / admin' })
  } catch (e) { res.status(500).json({ message: e.message }) }
})

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`)
})
